---
spring:
  application:
    name: springcloud-eureka-server
server:
  port: 8761
security:
  basic:
    enabled: false
  user:
    password: 314159
    name: science
eureka:
  instance:
    hostname: 127.0.0.1
    prefer-ip-address: true
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
